"""Generated by 'django-admin startproject' using Django 1.8.2."""

from __future__ import print_function
import os
import sys

PROJECT_NAME = 'echo_server'
PROJECT_TITLE = 'Echo Server'
CONF_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.dirname(CONF_DIR)
CONF_DIR_NAME = os.path.relpath(CONF_DIR, BASE_DIR)

SECRET_KEY = '$t+sfj_ex1*%h1m!q)e@t6#8#7tfai4qy4a6ujapykg@z_0$d2'
DEBUG = True
ALLOWED_HOSTS = ['*']

try:
	with open(os.path.join(CONF_DIR, "local", "secret_key.txt")) as _secret_key_file:
		SECRET_KEY = _secret_key_file.read().strip()
		DEBUG = False
except (OSError, IOError):
	print("Using default secret key (this is insecure)", file=sys.stderr)

# Application definition
INSTALLED_APPS = ()
MIDDLEWARE_CLASSES = ()
ROOT_URLCONF = 'echo_server.urls'
TEMPLATES = []
WSGI_APPLICATION = 'echo_server.wsgi.application'

# Database
DATABASES = {}

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_L10N = True
USE_TZ = True
