"""Generated by 'django-admin startproject' using Django 1.8.2."""

import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SECRET_KEY = '$t+sfj_ex1*%h1m!q)e@t6#8#7tfai4qy4a6ujapykg@z_0$d2'
DEBUG = True
ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = ()
MIDDLEWARE_CLASSES = ()
ROOT_URLCONF = 'echo_server.urls'
TEMPLATES = []
WSGI_APPLICATION = 'echo_server.wsgi.application'

# Database
DATABASES = {}

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_L10N = True
USE_TZ = True
